apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewogICAgICAgICAgICAgICAgImdoY3IuaW8iOiB7CiAgICAgICAgICAgICAgICAgICAgICAgICJhdXRoIjogIlIyRjBhVzVOU1RwbmFIQmZWemwxTkZGMGEybFNWWFF6YWpjM2JtZHVhR1Z1VDFOd05IUjJUSEpGTUZKUWJUUloiCiAgICAgICAgICAgICAgICB9IAoJfQp9
type: kubernetes.io/dockerconfigjson
